// Generated by CoffeeScript 2.6.1
window.addEventListener('load', function() {
  if (window.navigator.appVersion.match(/Windows|DOS/)) {
    return document.body.innerHTML = "<center style='font-size: 12rem;'>Windouser</center>";
  }
});
